show databases;

use resume;

SHOW TABLES;

CREATE TABLE USER_INFO (ID INTEGER PRIMARY KEY auto_increment, NAME VARCHAR(20), LOGIN_ID VARCHAR(20) UNIQUE,
       PASSWORD VARCHAR(100),  REG_DATE DATE, UPT_DATE DATE);
   
CREATE TABLE CATEGORY (ID VARCHAR(20) PRIMARY KEY, VALUE VARCHAR(40), TYPE VARCHAR(10) ); 

CREATE TABLE BROAD (ID INTEGER PRIMARY KEY auto_increment, USER_ID INTEGER, CATEGORY_ID VARCHAR(20),
	START_DATE VARCHAR(8) , END_DATE VARCHAR(8),
	ORG_NAME VARCHAR(40), ORG_PART VARCHAR(40), ORG_POS VARCHAR(40), ORG_RANK VARCHAR(40), 
    ORD INTEGER , REG_DATE DATE, UPT_DATE DATE);

CREATE TABLE DETAIL (ID INTEGER PRIMARY KEY auto_increment, BROAD_ID INTEGER , 
	TITLE VARCHAR(1000), DETAIL VARCHAR(1000),
	START_DATE VARCHAR(8) , END_DATE VARCHAR(8), 
	ORD INTEGER, REG_DATE DATE, UPT_DATE DATE);

CREATE TABLE USER_INFO_ROLES (USER_INFO_ID INTEGER , ROLES VARCHAR(20), REG_DATE DATE, UPT_DATE DATE);
       
DROP TABLE USER_INFO_ROLES;

select * from USER_INFO_ROLES;
select * from USER_INFO;